"use client";

import { motion } from "framer-motion";
import { NetworkBackground } from "@/components/ui/NetworkBackground";
import Link from "next/link";
import { AlertTriangle } from "lucide-react";

export default function RiskPage() {
  const fadeInUp = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.6 }
  };

  const stagger = {
    animate: {
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  return (
    <div className="min-h-screen bg-brand-deep-red text-brand-bone font-sans selection:bg-brand-bone/20">
      <div className="fixed inset-0 opacity-30 pointer-events-none">
        <NetworkBackground />
      </div>

      <div className="relative z-10 pt-32 pb-24 px-6 container mx-auto max-w-7xl">
        <motion.div 
          initial="initial"
          animate="animate"
          variants={fadeInUp}
        >
          <Link 
            href="/node"
            className="inline-block border border-brand-bone/20 px-4 py-1.5 mb-12 text-sm font-bold uppercase tracking-widest text-brand-bone hover:bg-brand-bone hover:text-brand-deep-red transition-colors"
          >
            ← Back to Node
          </Link>

          <div className="mb-8">
            <span className="text-sm font-bold uppercase tracking-widest text-brand-bone/60">
              Risk Disclosure
            </span>
          </div>

          <h1 className="text-5xl md:text-7xl lg:text-8xl font-bold uppercase leading-[0.85] tracking-tighter mb-8 text-brand-bone">
            Risk<br />
            Factors
          </h1>

          <p className="text-xl md:text-2xl text-brand-bone/80 mb-24 max-w-2xl font-light leading-relaxed">
            Participation in Nodebase infrastructure involves significant risks. 
            Potential participants should carefully consider the following factors before committing capital.
          </p>
        </motion.div>

        <motion.div 
          initial="initial"
          whileInView="animate"
          viewport={{ once: true }}
          variants={stagger}
          className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-12"
        >
          {[
            {
              id: "01",
              title: "No Guarantee of Returns",
              desc: "Nodebase does not guarantee any specific rate of return or profit. Returns are entirely dependent on the actual utilization of the infrastructure by paying customers of kaisa AI and Nodebase Space. If demand for these services is lower than anticipated, returns may be minimal or zero."
            },
            {
              id: "02",
              title: "Utilization & Market Risk",
              desc: "The value generated by a Node is directly tied to the commercial success of Nodebase's products. The AI and cloud storage markets are highly competitive. Technological shifts, new competitors, or changes in consumer preference could negatively impact the demand for our infrastructure."
            },
            {
              id: "03",
              title: "Hardware & Operational Risk",
              desc: "Physical infrastructure is subject to wear and tear, technical failures, and obsolescence. While we maintain comprehensive insurance and maintenance contracts, unforeseen catastrophic events (fire, flood, extended power outages) could disrupt operations and impact revenue generation. Hardware value depreciates over time."
            },
            {
              id: "04",
              title: "Regulatory Risk",
              desc: "The regulatory environment for digital infrastructure, AI, and data privacy in India is evolving. Changes in laws (such as the Digital Personal Data Protection Act) or new government policies could impose additional compliance costs or restrict our operational capabilities."
            },
            {
              id: "05",
              title: "Liquidity Risk",
              desc: "Nodes are illiquid assets. There is currently no secondary market for selling or trading Nodes. Participants should be prepared to hold their position for the full duration of the hardware lifecycle (typically 3-5 years). Early withdrawal is not permitted."
            }
          ].map((item) => (
            <motion.div key={item.id} variants={fadeInUp} className="flex flex-col gap-6 p-8 rounded-2xl border border-brand-bone/10 bg-brand-bone/5 hover:bg-brand-bone/10 transition-colors">
              <span className="text-xl font-bold text-brand-bone/40 border-b border-brand-bone/10 pb-2 w-fit">{item.id}</span>
              <h3 className="text-3xl font-bold uppercase tracking-tight leading-none text-brand-bone">
                {item.title}
              </h3>
              <p className="text-lg text-brand-bone/80 leading-relaxed">
                {item.desc}
              </p>
            </motion.div>
          ))}
        </motion.div>

        <motion.div 
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ delay: 0.5 }}
          className="mt-24 border border-brand-bone/20 p-8 md:p-12 rounded-2xl bg-brand-deep-red/50 backdrop-blur-sm"
        >
          <div className="flex items-start gap-4">
            <AlertTriangle className="w-6 h-6 text-brand-bone shrink-0 mt-1" />
            <p className="text-xl text-brand-bone/80 leading-relaxed">
              <strong>Disclaimer:</strong> This document is for informational purposes only and does not constitute an offer to sell or a solicitation of an offer to buy any securities. Nodebase recommends consulting with financial, legal, and tax advisors before making any participation decisions.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
