"use client";

import { AlertOctagon } from "lucide-react";

export default function RiskPage() {
  return (
    <div className="min-h-screen bg-black text-white py-20">
      <div className="container mx-auto px-6 max-w-3xl">
        
        <div className="mb-12 border-b border-white/10 pb-8">
          <div className="flex items-center gap-3 text-red-500 mb-4">
            <AlertOctagon className="w-8 h-8" />
            <span className="font-bold tracking-wider uppercase text-sm">Risk Disclosure</span>
          </div>
          <h1 className="text-4xl font-bold mb-6">Risk Factors</h1>
          <p className="text-lg text-white/60 leading-relaxed">
            Participation in Nodebase infrastructure involves significant risks. 
            Potential participants should carefully consider the following factors before committing capital.
          </p>
        </div>

        <div className="space-y-12">
          
          <section>
            <h2 className="text-xl font-bold text-white mb-4">1. No Guarantee of Returns</h2>
            <p className="text-white/70 leading-relaxed">
              Nodebase does not guarantee any specific rate of return or profit. Returns are entirely dependent on the actual utilization of the infrastructure by paying customers of kaisa AI and Nodebase Space. If demand for these services is lower than anticipated, returns may be minimal or zero.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">2. Utilization & Market Risk</h2>
            <p className="text-white/70 leading-relaxed">
              The value generated by a Node is directly tied to the commercial success of Nodebase's products. The AI and cloud storage markets are highly competitive. Technological shifts, new competitors, or changes in consumer preference could negatively impact the demand for our infrastructure.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">3. Hardware & Operational Risk</h2>
            <p className="text-white/70 leading-relaxed">
              Physical infrastructure is subject to wear and tear, technical failures, and obsolescence. While we maintain comprehensive insurance and maintenance contracts, unforeseen catastrophic events (fire, flood, extended power outages) could disrupt operations and impact revenue generation. Hardware value depreciates over time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">4. Regulatory Risk</h2>
            <p className="text-white/70 leading-relaxed">
              The regulatory environment for digital infrastructure, AI, and data privacy in India is evolving. Changes in laws (such as the Digital Personal Data Protection Act) or new government policies could impose additional compliance costs or restrict our operational capabilities.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">5. Liquidity Risk</h2>
            <p className="text-white/70 leading-relaxed">
              Nodes are illiquid assets. There is currently no secondary market for selling or trading Nodes. Participants should be prepared to hold their position for the full duration of the hardware lifecycle (typically 3-5 years). Early withdrawal is not permitted.
            </p>
          </section>

        </div>

        <div className="mt-16 p-6 glass-card rounded-xl text-sm text-white/50">
          <p>
            This document is for informational purposes only and does not constitute an offer to sell or a solicitation of an offer to buy any securities. 
            Nodebase recommends consulting with financial, legal, and tax advisors before making any participation decisions.
          </p>
        </div>

      </div>
    </div>
  );
}
