"use client";

import { useState } from "react";
import { Plus, Minus } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export default function FAQPage() {
  const faqs = [
    {
      q: "Who can become a Node?",
      a: "Participation is currently open to qualified individuals and institutional partners who meet our minimum capital requirements (₹10L) and pass KYC/AML verification. We prioritize partners aligned with a long-term infrastructure vision."
    },
    {
      q: "Where is the infrastructure located?",
      a: "All Phase 1 hardware is deployed at our primary Tier-IV data center in Okhla, New Delhi. This centralized facility allows us to maximize operational efficiency before expanding to additional geographic zones in Phase 2."
    },
    {
      q: "Is this equity in Nodebase?",
      a: "No. A Node represents a fractional ownership interest in a specific pool of physical infrastructure hardware and the revenue it generates. It does not convey equity ownership, voting rights, or governance in Nodebase the company."
    },
    {
      q: "Is this hardware ownership?",
      a: "Conceptually, yes. Your capital is used to purchase specific servers and equipment. However, Nodebase retains legal title and operational control to manage the fleet efficiently. You hold a contractual right to the revenue stream generated by that hardware."
    },
    {
      q: "Can I withdraw my capital?",
      a: "No. Capital deployed into hardware is illiquid for the lifecycle of the equipment (typically 3-5 years). Returns are distributed via quarterly payouts, but the principal cannot be withdrawn on demand."
    },
    {
      q: "How are payouts handled?",
      a: "Net revenue (Gross Revenue minus Power, Bandwidth, Space, and Management Fees) is calculated quarterly. Your share is directly transferred to your registered bank account within 15 days of the quarter's end."
    },
    {
      q: "When will dashboards be available?",
      a: "We are currently in Phase 1 (Infrastructure Deployment). The Investor Dashboard for real-time tracking of utilization and revenue is scheduled for release in Phase 2 (Q3 2024). Until then, partners receive monthly email reports."
    }
  ];

  return (
    <div className="min-h-screen bg-black text-white py-20">
      <div className="container mx-auto px-6 max-w-3xl">
        <h1 className="text-4xl font-bold mb-12">Frequently Asked Questions</h1>
        
        <div className="space-y-4">
          {faqs.map((faq, i) => (
            <FAQItem key={i} question={faq.q} answer={faq.a} />
          ))}
        </div>
      </div>
    </div>
  );
}

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border border-white/10 rounded-xl bg-white/5 overflow-hidden transition-colors hover:bg-white/10">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center justify-between w-full p-6 text-left"
      >
        <span className="font-medium text-lg text-white">{question}</span>
        {isOpen ? <Minus className="w-5 h-5 text-brand-saffron" /> : <Plus className="w-5 h-5 text-white/50" />}
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="p-6 pt-0 text-white/70 leading-relaxed border-t border-white/5 mt-2">
              {answer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
