
-- Migration 011: Autonomous Growth Engine
-- Infrastructure for AI-driven lead generation and proactive messaging.

CREATE TABLE IF NOT EXISTS public.growth_campaigns (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  type TEXT CHECK (type IN ('availability_gap', 'abandoned_inquiry', 'loyalty_upsell', 'review_boost')) NOT NULL,
  status TEXT CHECK (status IN ('active', 'paused', 'draft')) DEFAULT 'draft',
  trigger_config JSONB DEFAULT '{}'::jsonb, -- e.g. { "min_gap": 2, "horizon_days": 14 }
  message_template TEXT, -- AI prompt or base template
  auto_send BOOLEAN DEFAULT false,
  stats JSONB DEFAULT '{
    "total_reached": 0,
    "total_responses": 0,
    "total_conversions": 0,
    "revenue_generated": 0
  }'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Lead Opportunities (Drafts generated by Kaisa)
CREATE TABLE IF NOT EXISTS public.lead_opportunities (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
  campaign_id UUID REFERENCES public.growth_campaigns(id) ON DELETE CASCADE,
  guest_id UUID REFERENCES public.guests(id) ON DELETE CASCADE,
  listing_id UUID REFERENCES public.listings(id) ON DELETE CASCADE,
  opportunity_type TEXT NOT NULL, -- e.g. 'gap_filler'
  suggested_message TEXT NOT NULL,
  status TEXT CHECK (status IN ('pending', 'approved', 'sent', 'ignored')) DEFAULT 'pending',
  metadata JSONB DEFAULT '{}'::jsonb,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.growth_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_opportunities ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "tenant_isolation_growth_campaigns" ON public.growth_campaigns
  FOR ALL USING (tenant_id IN (SELECT tenant_id FROM public.tenant_users WHERE user_id = auth.uid()));

CREATE POLICY "tenant_isolation_lead_opportunities" ON public.lead_opportunities
  FOR ALL USING (tenant_id IN (SELECT tenant_id FROM public.tenant_users WHERE user_id = auth.uid()));

-- Indexes
CREATE INDEX IF NOT EXISTS idx_growth_campaigns_tenant ON public.growth_campaigns(tenant_id);
CREATE INDEX IF NOT EXISTS idx_lead_opportunities_tenant ON public.lead_opportunities(tenant_id);
CREATE INDEX IF NOT EXISTS idx_lead_opportunities_status ON public.lead_opportunities(status);
