"use client";

import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { motion } from "framer-motion";
import { NetworkBackground } from "@/components/ui/NetworkBackground";

const fadeInUp = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.6 }
};

const stagger = {
  animate: {
    transition: {
      staggerChildren: 0.1
    }
  }
};

export default function NodesPage() {
  return (
    <div className="flex flex-col min-h-screen bg-brand-deep-red text-brand-bone relative overflow-hidden font-sans selection:bg-brand-bone/20">
      <div className="fixed inset-0 opacity-30 pointer-events-none">
        <NetworkBackground />
      </div>
      
      {/* SECTION 1: HERO */}
      <section className="min-h-screen flex flex-col justify-center px-6 pt-24 pb-12 relative border-b border-brand-bone/10 z-10">
        <div className="max-w-7xl mx-auto w-full">
          <motion.div 
            initial="initial"
            animate="animate"
            variants={stagger}
          >
            <motion.div variants={fadeInUp}>
              <Link href="/node" className="text-sm font-bold uppercase tracking-widest border-b border-brand-bone/20 mb-12 inline-block hover:text-brand-bone/80 transition-colors">
                ← Back to Node
              </Link>
            </motion.div>
            
            <motion.h1 variants={fadeInUp} className="text-5xl md:text-8xl font-bold uppercase leading-[0.85] tracking-tighter mb-12 text-brand-bone">
              Node<br />
              Participation.
            </motion.h1>
            
            <motion.div variants={fadeInUp} className="grid grid-cols-1 md:grid-cols-2 gap-12 border-t border-brand-bone/20 pt-8">
              <p className="text-xl md:text-2xl text-brand-bone/80 font-light leading-relaxed max-w-md">
                A private, contractual participation in revenue generated by physical infrastructure deployed at our Okhla data center.
              </p>
              <div className="flex flex-col items-start justify-end">
                <div className="text-xl font-bold uppercase tracking-widest text-brand-bone">
                  Phase 1: Okhla, Delhi
                </div>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* SECTION 2: LEGAL NOTICE */}
      <section className="min-h-[50vh] flex flex-col justify-center px-6 py-24 border-b border-brand-bone/10 relative z-10">
        <div className="max-w-7xl mx-auto w-full">
           <motion.h2 
             initial={{ opacity: 0, y: 20 }}
             whileInView={{ opacity: 1, y: 0 }}
             viewport={{ once: true }}
             transition={{ duration: 0.6 }}
             className="text-5xl md:text-8xl font-bold uppercase leading-[0.85] tracking-tighter mb-16 text-brand-bone"
           >
            Regulatory<br />Notice.
          </motion.h2>
          
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="border border-brand-bone/20 p-8 md:p-12 bg-brand-bone/5"
          >
             <ul className="space-y-6">
                <li className="text-2xl font-bold uppercase tracking-tight flex items-start gap-4 text-brand-bone">
                  <span className="opacity-50 text-brand-bone">01</span> Not Equity in Nodebase
                </li>
                <li className="text-2xl font-bold uppercase tracking-tight flex items-start gap-4 text-brand-bone">
                  <span className="opacity-50 text-brand-bone">02</span> Not a Security
                </li>
                <li className="text-2xl font-bold uppercase tracking-tight flex items-start gap-4 text-brand-bone">
                  <span className="opacity-50 text-brand-bone">03</span> Not a SEBI-registered product
                </li>
                <li className="text-2xl font-bold uppercase tracking-tight flex items-start gap-4 text-brand-bone">
                  <span className="opacity-50 text-brand-bone">04</span> Not a public fundraising offer
                </li>
             </ul>
          </motion.div>
        </div>
      </section>

      {/* SECTION 3: UNIT ECONOMICS */}
      <section className="min-h-screen flex flex-col justify-center px-6 py-24 border-b border-brand-bone/10 relative z-10">
        <div className="max-w-7xl mx-auto w-full">
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-5xl md:text-8xl font-bold uppercase leading-[0.85] tracking-tighter mb-16 text-brand-bone"
          >
            Unit<br />Details.
          </motion.h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <p className="text-sm font-bold uppercase tracking-widest opacity-60 mb-4 text-brand-bone">
                Capital Deployment
              </p>
              <div className="text-6xl md:text-8xl font-bold tracking-tighter mb-4 text-brand-bone">
                ₹10L
              </div>
              <p className="text-xl text-brand-bone/80 font-light">
                Fixed capital per unit.
              </p>
            </motion.div>
            
             <motion.div 
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              <p className="text-sm font-bold uppercase tracking-widest opacity-60 mb-4 text-brand-bone">
                Structure
              </p>
              <div className="text-6xl md:text-8xl font-bold tracking-tighter mb-4 text-brand-bone">
                MoU
              </div>
              <p className="text-xl text-brand-bone/80 font-light">
                Bilateral revenue share agreement.
              </p>
            </motion.div>
          </div>

           <motion.div 
             initial={{ opacity: 0, y: 20 }}
             whileInView={{ opacity: 1, y: 0 }}
             viewport={{ once: true }}
             transition={{ duration: 0.6, delay: 0.4 }}
             className="mt-24 border-t border-brand-bone/20 pt-12"
           >
              <h3 className="text-2xl font-bold uppercase tracking-tight mb-8 text-brand-bone">
                Capital Allocation
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                <div>
                   <div className="text-4xl font-bold mb-2 text-brand-bone">70%</div>
                   <div className="text-sm uppercase tracking-widest opacity-60 text-brand-bone">Hardware Procurement</div>
                </div>
                <div>
                   <div className="text-4xl font-bold mb-2 text-brand-bone">15%</div>
                   <div className="text-sm uppercase tracking-widest opacity-60 text-brand-bone">Operations & Setup</div>
                </div>
                <div>
                   <div className="text-4xl font-bold mb-2 text-brand-bone">10%</div>
                   <div className="text-sm uppercase tracking-widest opacity-60 text-brand-bone">Legal & Compliance</div>
                </div>
                <div>
                   <div className="text-4xl font-bold mb-2 text-brand-bone">05%</div>
                   <div className="text-sm uppercase tracking-widest opacity-60 text-brand-bone">Reserve Fund</div>
                </div>
              </div>
           </motion.div>
        </div>
      </section>

      {/* SECTION 4: CTA */}
       <section className="min-h-[50vh] flex flex-col justify-center px-6 py-24 relative z-10">
        <div className="max-w-7xl mx-auto w-full text-center">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-5xl md:text-8xl font-bold uppercase leading-[0.85] tracking-tighter mb-12 text-brand-bone">
              Secure<br />Allocation.
            </h2>
            
            <Link 
              href="/node/apply"
              className="inline-flex items-center gap-6 text-3xl md:text-5xl font-bold uppercase tracking-tighter border-b-4 border-brand-bone pb-2 hover:gap-8 transition-all text-brand-bone"
            >
              Start Application <ArrowRight className="w-8 h-8 md:w-12 md:h-12" />
            </Link>
          </motion.div>
        </div>
      </section>

    </div>
  );
}
