"use client";

import { AlertTriangle, Info, CheckCircle2, Clock, ShieldCheck, Scale, Cpu, Network } from "lucide-react";
import Link from "next/link";
import { RoiCalculator } from "@/components/node/RoiCalculator";

export default function NodesPage() {
  return (
    <div className="min-h-screen bg-black text-white py-20">
      <div className="container mx-auto px-6 max-w-4xl">
        
        {/* Header with Legal Positioning */}
        <div className="mb-16 border-b border-white/10 pb-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-saffron/10 text-brand-saffron text-xs font-medium mb-6">
            <Info className="w-3 h-3" />
            <span>Phase 1 Allocation: Okhla, Delhi Facility</span>
          </div>
          <h1 className="text-4xl font-bold mb-6">Node Participation</h1>
          <p className="text-xl text-white/60 leading-relaxed max-w-2xl mb-8">
            A private, contractual participation in revenue generated by physical infrastructure deployed at our Okhla data center. 
            Executed via a bilateral MoU with Chishti Ventures Private Limited.
          </p>

          <div className="bg-white/5 rounded-xl p-6 border border-white/10 text-sm space-y-3">
             <div className="flex items-start gap-3">
               <AlertTriangle className="w-4 h-4 text-brand-saffron shrink-0 mt-0.5" />
               <div className="space-y-2">
                 <p className="text-white/80 font-medium">Important Regulatory Notice:</p>
                 <ul className="grid md:grid-cols-2 gap-x-8 gap-y-2 text-white/60 list-disc list-inside">
                   <li>Not Equity in Nodebase</li>
                   <li>Not a Security</li>
                   <li>Not a SEBI-registered product</li>
                   <li>Not a public fundraising offer</li>
                 </ul>
               </div>
             </div>
          </div>
        </div>

        {/* Core Details Grid */}
        <div className="grid md:grid-cols-2 gap-8 mb-16">
          <div className="glass-card p-8 rounded-2xl hover:bg-white/10 transition-colors">
            <h3 className="text-sm font-medium text-white/50 uppercase tracking-wider mb-2">Node Unit Size</h3>
            <div className="text-4xl font-bold text-white mb-2">₹10,00,000</div>
            <p className="text-sm text-white/40">Fixed capital deployment per unit</p>
          </div>

          <div className="glass-card p-8 rounded-2xl">
            <h3 className="text-sm font-medium text-white/50 uppercase tracking-wider mb-2">Structure</h3>
            <div className="text-4xl font-bold text-white mb-2">Contractual</div>
            <p className="text-sm text-white/40">Revenue share via MoU</p>
          </div>
        </div>

        {/* Deployment of Capital */}
        <div className="mb-16">
          <h2 className="text-2xl font-bold mb-8">Capital Allocation Model</h2>
          <p className="text-white/60 mb-8 max-w-2xl">
            Capital is tied directly to physical infrastructure. Nodebase retains legal ownership and operational control, 
            while participants hold a contractual right to revenue generated by the infrastructure pool.
          </p>
          
          <div className="space-y-4">
             {[
               { 
                 pct: "70%", 
                 title: "Hardware Procurement", 
                 desc: "Direct purchase of GPUs, compute servers, storage arrays, and networking gear.",
                 icon: Cpu 
               },
               { 
                 pct: "20%", 
                 title: "Operational Expenses", 
                 desc: "Power, bandwidth, colocation fees, cooling systems, and NOC operations.",
                 icon: ShieldCheck
               },
               { 
                pct: "10%", 
                title: "Facility Optimization", 
                desc: "Redundancy buffers, network switches, and rack-level optimization within the Okhla facility.",
                icon: Network 
              }
            ].map((item, i) => (
              <div key={i} className="flex gap-6 p-6 glass-card rounded-xl hover:bg-white/10 transition-colors items-center">
                <div className="w-16 h-16 rounded-full bg-white/5 flex items-center justify-center shrink-0 border border-white/10 font-bold text-xl text-brand-saffron">
                  {item.pct}
                </div>
                <div>
                  <h3 className="font-bold text-white mb-1 flex items-center gap-2">
                    {item.title}
                    {/* <item.icon className="w-4 h-4 text-white/40" /> */}
                  </h3>
                  <p className="text-sm text-white/60">{item.desc}</p>
                </div>
              </div>
            ))}
         </div>
       </div>

       {/* Deployment & Hold Period Timeline */}
       <div className="mb-16">
         <h2 className="text-2xl font-bold mb-8 flex items-center gap-3">
           <Clock className="w-6 h-6 text-brand-saffron" />
           Deployment Timeline (Okhla)
         </h2>
         
         <div className="relative border-l border-white/10 ml-3 space-y-12 py-4">
           {[
             { time: "Month 0–1", title: "Allocation & Procurement", desc: "MoU execution, capital allocation, and initiation of vendor procurement for the Okhla site." },
             { time: "Month 1–2", title: "Installation & Provisioning", desc: "Hardware delivery, rack installation, and power provisioning at the data center." },
             { time: "Month 2–3", title: "Testing & Integration", desc: "Redundancy checks and integration with Nodebase Space and kaisa AI workloads." },
             { time: "Month 3+", title: "Revenue Activation", desc: "Infrastructure becomes revenue-active. Early participation benefits from centralized operations.", active: true }
           ].map((step, i) => (
              <div key={i} className="relative pl-10">
                <div className={`absolute -left-[5px] top-2 w-2.5 h-2.5 rounded-full ${step.active ? 'bg-brand-saffron shadow-[0_0_10px_rgba(255,193,7,0.5)]' : 'bg-white/20'}`} />
                <span className="text-xs font-bold text-brand-saffron uppercase tracking-wider mb-1 block">{step.time}</span>
                <h3 className="text-lg font-bold text-white mb-2">{step.title}</h3>
                <p className="text-white/60 text-sm leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>

          <div className="mt-8 p-4 bg-white/5 rounded-lg border border-white/10 text-sm text-white/50 flex gap-3">
            <Scale className="w-5 h-5 shrink-0" />
            <p>
              Capital is locked during the deployment phase. Participation aligns with the hardware lifecycle (typically 3–5 years). No early withdrawal permitted.
            </p>
          </div>
        </div>

        {/* ROI Calculator */}
        <div className="mb-16">
           <h2 className="text-2xl font-bold mb-8">Estimated Performance</h2>
           <RoiCalculator />
        </div>

        {/* Disclaimer / Next Steps */}
        <div className="flex flex-col md:flex-row gap-8 items-start border-t border-white/10 pt-10">
           <div className="flex-1">
             <div className="flex items-start gap-3 p-4 bg-red-500/10 border border-red-500/20 rounded-lg text-red-200 text-sm">
               <AlertTriangle className="w-5 h-5 shrink-0" />
               <p>
                 <strong>Risk Warning:</strong> Infrastructure participation involves risks including hardware depreciation, market demand fluctuations, and regulatory changes. 
                 Nodebase does not guarantee any fixed returns or capital protection.
               </p>
             </div>
           </div>
           <div className="flex-shrink-0">
             <Link href="/company/contact" className="block w-full md:w-auto text-center px-8 py-4 bg-white text-black rounded-lg font-bold hover:bg-gray-200 transition-colors">
               Request Participation
             </Link>
             <p className="text-xs text-white/30 text-center mt-3">Invite-based process.</p>
           </div>
        </div>

      </div>
    </div>
  );
}
